### ISSUE TITLE
More specific sub-categories

### ISSUE THREAD

**Issue by cmgriffing** [owenbcoding/my-resources#2]
It would be cool to group specific tools together more.

example:
- Replit a online Browser text editor https://replit.com/
- Codeply HTML - CSS & Js Editor https://www.codeply.com/
- Code Sand box A browser text editor https://codesandbox.io/
- Code pen another browser playground https://codepen.io/
- A playground for practicing js https://jsbin.com/

These could all be under a "Online Playgrounds" or something like it.

**Comment by owenbcoding** [comment]
Added some extra categories to the list as you suggested
